services:
  mysql:
    image: mysql:8.0
    container_name: cineverse-mysql
    environment:
      MYSQL_DATABASE: cineverse
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cineverse
      MYSQL_PASSWORD: cineverse
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: cineverse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: